version: '3.5'
services:
    postgresql:
        image: postgres:13-alpine
        container_name: postgresql
        environment:
            - POSTGRES_DB=auth_users
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - PGDATA=/data/postgres
        ports:
            - 15433:5433
        command: -p 5433
        volumes:
            - postgres_volume:/data/postgres
        networks:
            - internal_comunication_auth_api

    auth_api:
        build: .
        container_name: auth_api
        ports: 
            - 80:80
        networks:
            - internal_comunication_auth_api
            - internal_comunication

networks:
    internal_comunication_auth_api:
        external: true
        name: internal_comunication_auth_api
    internal_comunication:
        external: true
        name: internal_comunication