version: '3.5'
services:
    postgresql_auth:
        build:
            context: .
            dockerfile: psqlDockerfile
        container_name: postgresql_auth
        environment:
            - POSTGRES_DB=auth_users
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - PGDATA=/data/postgres
        ports:
            - 15433:5433
        command: echo "aaaaaaaaaaaa"
        command: -p 5433
        volumes:
            - postgres_volume:/data/postgres
            - ./utils/tables/auth_table.sql:/docker-entrypoint-initdb.d/1.sql
        networks:
            - internal_comunication_auth_api

    auth_api:
        build: .
        depends_on: 
            - postgresql_auth
        container_name: auth_api
        environment: 
            - TOKEN_SECRET=lkdfkljgkergjmnkdfdfdf11
        ports: 
            - 81:81
        networks:
            - internal_comunication_auth_api
            - internal_comunication

networks:
    internal_comunication_auth_api:
        external: true
        name: internal_comunication_auth_api
    internal_comunication:
        external: true
        name: internal_comunication

volumes:
    postgres_volume: