version: '3.7'
services:
    mongodb:
        image: mongo:latest
        container_name: mongdb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword
        ports:
        - 27017:27017
        volumes:
        - mongodb_data_container:/data/db


volumes:
    mongodb_data_container:

networks:
    internal_comunication:
        external: true
        name: internal_comunication