version: '3.5'
services:
    mysql-container:
        image: postgres
        environment:
            - POSTGRES_DB=clients
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=senhasecreta
        ports:
            - "15432:5432"
        volumes:
            - "./data:/var/lib/postgresql/data"
        networks:
            - internal_comunication

networks:
    internal_comunication:
        external: true
        name: internal_comunication