version: '3.5'
services:
    postgresql:
        image: postgres:13-alpine
        container_name: postgresql
        environment:
            - POSTGRES_DB=citzens_financial_data
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - PGDATA=/data/postgres
        ports:
            - 5432:5432
        volumes:
            - postgres_volume:/data/postgres
            - ./utils/tables/citzen_table.sql:/docker-entrypoint-initdb.d/1.sql
            - ./utils/tables/address.sql:/docker-entrypoint-initdb.d/2.sql
            - ./utils/tables/debts.sql:/docker-entrypoint-initdb.d/3.sql
        networks:
            - internal_comunication

volumes:
    postgres_volume:

networks:
    internal_comunication:
        external: true
        name: internal_comunication