version: '3.5'
services:
    postgresql:
        image: postgres
        container_name: postgresql
        environment:
            - POSTGRES_DB=clients
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=senhasecreta
        ports:
            - "15432:5432"
        volumes:
            - "postgres_volume:/var/lib/postgresql/data"
        networks:
            - internal_comunication

volumes:
    postgres_volume:

networks:
    internal_comunication:
        external: true
        name: internal_comunication