version: '3.5'
services:
    nginx:
        image: nginx:latest
        ports:
        - "80:80"
        volumes:
        - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
        networks:
            - internal_comunication
networks: 
    internal_comunication:
        external:
            name: internal_comunication