definitions:
  delivery.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  delivery.Response:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Citizen'
        type: array
      message:
        type: string
    type: object
  delivery.ResponseAddress:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Address'
        type: array
      message:
        type: string
    type: object
  delivery.ResponseDebt:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Debt'
        type: array
      message:
        type: string
    type: object
  domain.Address:
    properties:
      address:
        type: string
      citizen_id:
        type: integer
      city:
        type: string
      complement:
        type: string
      country:
        type: string
      deleted:
        default: false
        type: boolean
      id:
        type: integer
      neighbourhood:
        type: string
      number:
        default: "false"
        type: string
      postal_code:
        type: string
      state:
        type: string
    type: object
  domain.Citizen:
    properties:
      address:
        items:
          $ref: '#/definitions/domain.Address'
        type: array
      cpf:
        type: string
      debts:
        items:
          $ref: '#/definitions/domain.Debt'
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
  domain.Debt:
    properties:
      credit_taken_at:
        type: string
      credit_turned_debit_at:
        type: string
      debtor_id:
        type: integer
      deleted:
        default: false
        type: boolean
      id:
        type: integer
      value:
        type: number
      was_negociated:
        default: false
        type: boolean
    type: object
info:
  contact: {}
paths:
  /citizen:
    get:
      consumes:
      - application/json
      parameters:
      - description: Offset for pagination in request
        in: query
        name: offset
        type: integer
      - description: Limit how many citizens will be returned
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Get a list of citizens
      tags:
      - Citizen
    post:
      consumes:
      - application/json
      parameters:
      - description: Citizen can have many addresses and debts
        in: body
        name: citizen_data
        required: true
        schema:
          $ref: '#/definitions/domain.Citizen'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Insert a new citizen data
      tags:
      - Citizen
  /citizen/{CPF}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 'Citizen CPF to return '
        in: path
        name: CPF
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Get a citizen data
      tags:
      - Citizen
    put:
      consumes:
      - application/json
      parameters:
      - description: Citizen CPF to update
        in: path
        name: CPF
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Update citizen data
      tags:
      - Citizen
  /citizen/{CPF}/address:
    get:
      consumes:
      - application/json
      parameters:
      - description: CPF of the address
        in: path
        name: CPF
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ResponseAddress'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Get a list of address
      tags:
      - Citizen
    post:
      consumes:
      - application/json
      parameters:
      - description: CPF of the citizen
        in: path
        name: CPF
        type: string
      - description: Address data
        in: body
        name: address_data
        required: true
        schema:
          $ref: '#/definitions/domain.Address'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ResponseAddress'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Insert a new Address
      tags:
      - Citizen
  /citizen/{CPF}/address/{ID}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: CPF of the citizen
        in: path
        name: CPF
        type: string
      - description: Id of the Address
        in: path
        name: ID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ResponseAddress'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Delete a specific Address
      tags:
      - Citizen
    put:
      consumes:
      - application/json
      parameters:
      - description: CPF of the citizen
        in: path
        name: CPF
        type: string
      - description: Id of the Address
        in: path
        name: ID
        type: string
      - description: Address data
        in: body
        name: address_data
        required: true
        schema:
          $ref: '#/definitions/domain.Address'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ResponseAddress'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Update a specific Address
      tags:
      - Citizen
  /citizen/{CPF}/debts:
    get:
      consumes:
      - application/json
      parameters:
      - description: CPF of the citizen
        in: path
        name: CPF
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ResponseDebt'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Get a list of debts
      tags:
      - Citizen
    post:
      consumes:
      - application/json
      parameters:
      - description: CPF of the citizen
        in: path
        name: CPF
        type: string
      - description: Debt data
        in: body
        name: debt_data
        required: true
        schema:
          $ref: '#/definitions/domain.Debt'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ResponseDebt'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Insert a new debt
      tags:
      - Citizen
  /citizen/{CPF}/debts/{ID}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: CPF of the citizen
        in: path
        name: CPF
        type: string
      - description: Id of the debt
        in: path
        name: ID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ResponseDebt'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Delete a specific debt
      tags:
      - Citizen
    put:
      consumes:
      - application/json
      parameters:
      - description: CPF of the citizen
        in: path
        name: CPF
        type: string
      - description: Id of the debt
        in: path
        name: ID
        type: string
      - description: Debt data
        in: body
        name: debt_data
        required: true
        schema:
          $ref: '#/definitions/domain.Debt'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ResponseDebt'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Update a specific debt
      tags:
      - Citizen
swagger: "2.0"
